name: Deploy to GitHub Pages (PAT)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: "Ari10/Desarrollo de Software/CATO/Tercer Semestre/Proyecto Integrador/Clode/front"
        run: npm ci

      - name: Build
        working-directory: "Ari10/Desarrollo de Software/CATO/Tercer Semestre/Proyecto Integrador/Clode/front"
        run: npm run build

      - name: Publish to gh-pages with PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_PAT }}
          publish_branch: gh-pages
          publish_dir: "Ari10/Desarrollo de Software/CATO/Tercer Semestre/Proyecto Integrador/Clode/front/dist"
          force_orphan: true
          enable_jekyll: false
