name: Deploy to GitHub Pages (PAT)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Si tu sitio es estático puro, no hay build. Si usas Vite/React, agrega build aquí.
      # - name: Build
      #   run: |
      #     npm ci
      #     npm run build

      - name: Publish to gh-pages with PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_PAT }}  
          publish_branch: gh-pages
          publish_dir: ./public                     
          force_orphan: true
